#!/bin/sh
#
# Start the pppd daemon - 4G modem
#

RUN_DAEMON="pppd call tele2"
MODEM_PORT="/dev/ttyUSB3"


case "$1" in
  start)
        printf "Starting pppd"
	timeout=5
	while [ ${timeout} != 0 ] && [ ! -e ${MODEM_PORT} ]
	do
	        printf "."
		sleep 2
		timeout=$((timeout - 1))
	done
	if [ $timeout -ne 0 ]; then
		printf ": "
        	$RUN_DAEMON
	        [ $? = 0 ] && echo "OK" || echo "FAIL"
	else
		echo "FAIL - Timeout waiting for ${MODEM_PORT} to appear."
	fi
        ;;
  stop)
        printf "Stopping pppd: "
        /usr/bin/killall -q pppd
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
